# Site settings
email: 
baseurl:
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Anna Kennedy's blog
description: Anna Kennedy
url: ""
twitter_username: 
default_img: 

# Profile settings
name: Anna Kennedy
profile_img: 
profile: 
social:
  github: 

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
