# Site settings
email: 
baseurl:
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-91008296-1

# SEO settings
title: Ordinary Route
description: Ordinary Route
url: ""
twitter_username: 
default_img: 

# Profile settings
name: Anna Kennedy
profile_img: "/assets/images/anna.jpg"
profile: "Anna spends all of her free time exploring the outdoors, including winter climbing, trad climbing, mountaineering, skiing, and hiking. If it's an adventure, she's happy."
social:
  instagram: "https://www.instagram.com/anna_ken_/"

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
